"use client";
import { ArrowUpRight, Clock3 } from "lucide-react";
import { t } from "@/lib/translations";
import type { Locale, Service, ServiceCategory } from "@/lib/types";
import { barberLabels, formatServicePrice, getCategoryLabel } from "../barber-utils";
type Props = { categories: ServiceCategory[]; currency: string; locale: Locale; services: Service[]; onBookService: (serviceId: string) => void };
export default function BarberMobileServicesSection({ categories, currency, locale, services, onBookService }: Props) {
  return <section id="barber-mobile-services" className="border-y border-[var(--brand-border)] bg-[var(--brand-surface)] py-11"><div className="px-5"><p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-[var(--brand-primary)]">01 / {t(barberLabels.navServices, locale)}</p><h2 className="font-display mt-4 text-4xl font-medium leading-[0.92] tracking-[-0.04em]">{t(barberLabels.servicesTitle, locale)}</h2></div><div className="mt-8 space-y-2 px-3">{services.map((service, index) => <article key={service.id} className="rounded-[1.35rem] border border-[var(--brand-border)] bg-[var(--brand-background)] p-4"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="text-[9px] font-semibold uppercase tracking-[0.18em] text-[var(--brand-primary)]">{String(index + 1).padStart(2, "0")} / {getCategoryLabel(service, categories, locale)}</p><h3 className="font-display mt-2 text-2xl font-medium">{t(service.name, locale)}</h3></div><p className="shrink-0 text-sm font-semibold">{formatServicePrice(service, currency, locale)}</p></div>{service.description && <p className="mt-3 line-clamp-2 text-sm leading-6 text-[var(--brand-muted)]">{t(service.description, locale)}</p>}<div className="mt-4 flex items-center justify-between border-t border-[var(--brand-border)] pt-4"><span className="inline-flex items-center gap-2 text-xs text-[var(--brand-muted)]"><Clock3 className="h-3.5 w-3.5" aria-hidden="true"/>{service.durationMinutes} {t(barberLabels.minutes, locale)}</span><button type="button" onClick={() => onBookService(service.id)} className="inline-flex min-h-10 items-center gap-2 rounded-full bg-[var(--brand-primary)] px-4 text-xs font-semibold text-[var(--brand-background)]">{t(barberLabels.bookService, locale)}<ArrowUpRight className="h-3.5 w-3.5" aria-hidden="true"/></button></div></article>)}{services.length === 0 && <div className="rounded-[1.35rem] border border-dashed border-[var(--brand-border)] px-5 py-12 text-center text-sm text-[var(--brand-muted)]">{t(barberLabels.servicesEmpty, locale)}</div>}</div></section>;
}
