"use client";
import { CalendarPlus, Mail, MapPin, Monitor, Phone } from "lucide-react";
import InstagramIcon from "@/components/shared/icons/InstagramIcon";
import { t } from "@/lib/translations";
import type { CatalogBusiness, Locale } from "@/lib/types";
import { barberLabels } from "../barber-utils";
type Props = { business: CatalogBusiness; locale: Locale; locationLine: string; onBook: () => void; onSwitchToDesktop: () => void };
export default function BarberMobileContactSection({ business, locale, locationLine, onBook, onSwitchToDesktop }: Props) {
  return <section id="barber-mobile-contact" className="px-3 py-12"><div className="rounded-[1.7rem] bg-[var(--brand-primary)] p-6 text-[var(--brand-background)]"><p className="text-[10px] font-semibold uppercase tracking-[0.22em] opacity-60">04 / {t(barberLabels.navContact, locale)}</p><h2 className="font-display mt-5 text-5xl font-medium leading-[0.88] tracking-[-0.05em]">{t(barberLabels.contactTitle, locale)}</h2><div className="mt-8 space-y-5">{locationLine && <div className="flex items-start gap-3"><MapPin className="mt-0.5 h-5 w-5 shrink-0" aria-hidden="true"/><span className="text-sm font-medium leading-6">{locationLine}</span></div>}{business.phone && <a href={`tel:${business.phone}`} className="flex items-center gap-3 text-sm font-medium"><Phone className="h-5 w-5" aria-hidden="true"/>{business.phone}</a>}{business.email && <a href={`mailto:${business.email}`} className="flex items-center gap-3 break-all text-sm font-medium"><Mail className="h-5 w-5" aria-hidden="true"/>{business.email}</a>}{business.instagramUrl && <a href={business.instagramUrl} target="_blank" rel="noreferrer" className="flex items-center gap-3 text-sm font-medium"><InstagramIcon className="h-5 w-5" aria-hidden="true"/>{business.instagramHandle || "Instagram"}</a>}</div><button type="button" onClick={onBook} className="mt-8 inline-flex min-h-13 w-full items-center justify-between rounded-full bg-[var(--brand-background)] px-5 text-sm font-semibold text-[var(--brand-text)]">{t(barberLabels.bookAppointment, locale)}<CalendarPlus className="h-5 w-5" aria-hidden="true"/></button></div><button type="button" onClick={onSwitchToDesktop} className="mt-5 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-full border border-[var(--brand-border)] text-xs font-semibold text-[var(--brand-muted)]"><Monitor className="h-4 w-4" aria-hidden="true"/>{t(barberLabels.openDesktop, locale)}</button></section>;
}
