"use client";
import Image from "next/image";
import { ArrowUpRight, Scissors } from "lucide-react";
import { t } from "@/lib/translations";
import type { Employee, Locale } from "@/lib/types";
import { barberLabels } from "../barber-utils";

type Props = { employees: Employee[]; locale: Locale; onBookEmployee: (employeeId: string) => void };
export default function BarberDesktopTeamSection({ employees, locale, onBookEmployee }: Props) {
  return <section id="barbers" className="mx-auto max-w-[1500px] px-8 py-24 xl:px-12 xl:py-32"><div className="flex items-end justify-between gap-10"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-[var(--brand-primary)]">02 / {t(barberLabels.navBarbers, locale)}</p><h2 className="font-display mt-6 max-w-3xl text-6xl font-medium leading-[0.9] tracking-[-0.045em]">{t(barberLabels.barbersTitle, locale)}</h2></div><div className="hidden items-center gap-3 text-sm text-[var(--brand-muted)] xl:flex"><Scissors className="h-5 w-5 text-[var(--brand-primary)]" aria-hidden="true"/>{t(barberLabels.heroTrust2, locale)}</div></div>
    <div className="mt-16 grid grid-cols-4 gap-5">{employees.map((employee, index) => <article key={employee.id} className={`group ${index % 2 === 1 ? "mt-12" : ""}`}><div className="relative aspect-[4/5] overflow-hidden rounded-[1.4rem] border border-[var(--brand-border)] bg-[var(--brand-surface)]">{employee.image ? <Image src={employee.image} alt={employee.name} fill className="object-cover grayscale-[28%] transition duration-700 group-hover:scale-105 group-hover:grayscale-0" sizes="25vw"/> : <div className="absolute inset-0 flex items-center justify-center bg-[radial-gradient(circle_at_50%_25%,color-mix(in_srgb,var(--brand-primary)_24%,transparent),transparent_36%),linear-gradient(145deg,var(--brand-secondary),var(--brand-surface))]"><span className="font-display text-7xl text-[var(--brand-primary)]/60">{employee.name.charAt(0)}</span></div>}<div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-black/10"/><button type="button" onClick={() => onBookEmployee(employee.id)} className="absolute bottom-5 right-5 flex h-12 w-12 items-center justify-center rounded-full bg-[var(--brand-primary)] text-[var(--brand-background)]" aria-label={`${t(barberLabels.bookBarber, locale)} ${employee.name}`}><ArrowUpRight className="h-5 w-5" aria-hidden="true"/></button><div className="absolute bottom-5 left-5 right-20 text-white"><h3 className="font-display text-2xl font-medium">{employee.name}</h3>{employee.role && <p className="mt-1 text-xs font-semibold uppercase tracking-[0.14em] text-[var(--brand-primary)]">{t(employee.role, locale)}</p>}</div></div>{employee.bio && <p className="mt-5 line-clamp-3 px-1 text-sm leading-6 text-[var(--brand-muted)]">{t(employee.bio, locale)}</p>}</article>)}{employees.length === 0 && <div className="col-span-4 rounded-[1.6rem] border border-dashed border-[var(--brand-border)] px-8 py-20 text-center text-[var(--brand-muted)]">{t(barberLabels.barbersEmpty, locale)}</div>}</div>
  </section>;
}
